apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: eshop-currencyservice
      context: eshop-currencyservice
    - image: eshop-recommendservice
      context: eshop-recommendservice
    - image: eshop-productservice
      context: eshop-productservice
    - image: eshop-adservice
      context: eshop-adservice
      jib: {}
    - image: eshop-cartservice
      context: eshop-cartservice
      jib: {}
    - image: eshop-backend
      context: eshop-backend
      jib: {}
    - image: eshop-frontend
      context: eshop-frontend
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml